# Site Specific Configuration
name: David "Grant" McAllister Jr. 
description: My personal site
url: https://https://grantmca.github.io/
author: grantmca 
timezone: America/Chicago
timezone_short: CST

# Keywords
keywords: ['seo', 'key', 'words']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

